//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Messages.proto
namespace TestSOA.PortfolioManagement.Messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CalculateDirtyPnlRequest")]
  public partial class CalculateDirtyPnlRequest: TestSOA.Messaging.Request, global::ProtoBuf.IExtensible
  {
    public CalculateDirtyPnlRequest() {}
    
    private int _PositionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PositionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PositionId
    {
      get { return _PositionId; }
      set { _PositionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CalculateDirtyPnlResponse")]
  public partial class CalculateDirtyPnlResponse: TestSOA.Messaging.Response, global::ProtoBuf.IExtensible
  {
    public CalculateDirtyPnlResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PnlRecalculatedEvent")]
  public partial class PnlRecalculatedEvent: TestSOA.Messaging.Event, global::ProtoBuf.IExtensible
  {
    public PnlRecalculatedEvent() {}
    
    private int _PositionId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PositionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PositionId
    {
      get { return _PositionId; }
      set { _PositionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
