//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Messages.proto
namespace TestSOA.ReferenceData.Messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostSecurityRequest")]
  public partial class PostSecurityRequest: TestSOA.Messaging.Request, global::ProtoBuf.IExtensible
  {
    public PostSecurityRequest() {}
    
    private string _CUSIP;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"CUSIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CUSIP
    {
      get { return _CUSIP; }
      set { _CUSIP = value; }
    }
    private string _ISIN;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ISIN", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ISIN
    {
      get { return _ISIN; }
      set { _ISIN = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PostSecurityResponse")]
  public partial class PostSecurityResponse: TestSOA.Messaging.Response, global::ProtoBuf.IExtensible
  {
    public PostSecurityResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SecurityPostedEvent")]
  public partial class SecurityPostedEvent: TestSOA.Messaging.Event, global::ProtoBuf.IExtensible
  {
    public SecurityPostedEvent() {}
    
    private int _SecurityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SecurityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SecurityId
    {
      get { return _SecurityId; }
      set { _SecurityId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
