//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Messages.proto
namespace TestSOA.OrderManagement.Messages
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestCommand")]
  public partial class TestCommand: global::ProtoBuf.IExtensible
  {
    public TestCommand() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitOrderRequest")]
  public partial class SubmitOrderRequest: TestSOA.Messaging.Request, global::ProtoBuf.IExtensible
  {
    public SubmitOrderRequest() {}
    
    private int _SecurityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SecurityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SecurityId
    {
      get { return _SecurityId; }
      set { _SecurityId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SubmitOrderResponse")]
  public partial class SubmitOrderResponse: TestSOA.Messaging.Response, global::ProtoBuf.IExtensible
  {
    public SubmitOrderResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderSubmittedEvent")]
  public partial class OrderSubmittedEvent: TestSOA.Messaging.Event, global::ProtoBuf.IExtensible
  {
    public OrderSubmittedEvent() {}
    
    private int _OrderId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OrderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OrderId
    {
      get { return _OrderId; }
      set { _OrderId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BookOrderRequest")]
  public partial class BookOrderRequest: TestSOA.Messaging.Request, global::ProtoBuf.IExtensible
  {
    public BookOrderRequest() {}
    
    private int _OrderId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OrderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OrderId
    {
      get { return _OrderId; }
      set { _OrderId = value; }
    }

    private string _Note = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Note", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Note
    {
      get { return _Note; }
      set { _Note = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BookOrderResponse")]
  public partial class BookOrderResponse: TestSOA.Messaging.Response, global::ProtoBuf.IExtensible
  {
    public BookOrderResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderBookedEvent")]
  public partial class OrderBookedEvent: TestSOA.Messaging.Event, global::ProtoBuf.IExtensible
  {
    public OrderBookedEvent() {}
    
    private int _OrderId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OrderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OrderId
    {
      get { return _OrderId; }
      set { _OrderId = value; }
    }

    private string _Note = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Note", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Note
    {
      get { return _Note; }
      set { _Note = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
